### ISSUE TITLE
[patch] acs override for virtualization with gpu passthrough

### ISSUE THREAD

**Issue by hepp3n** [bazzite-org/kernel-bazzite#2]
Hi,

Could you please consider adding ACS Override Patch to this kernel for future Bazzite releases? Right now Bazzite have easy `ujust` scripts for setup virtualization even with gpu passthrough. The problem is when using multiple GPU and passing through one of them in the same groups of IOMMU.

This patch solves this problems. Before it was present in fsync kernel until some of the relases, I don't remember. It should not harm much since you need to enable this patch on your userspace with kernel params. So security should not be affected.

Are there any more problems with it to be not added? It's really, really helpful in many cases of GPU Passthrough.

**Comment by HikariKnight** [comment]
Hi, the ACS override is a hacky workaround for motherboards with bad IOMMU groups and will have to be updated constantly for the new kernel versions as things changes, this is not maintenance work we want to do.
It was also removed from fsync last year due to it [causing stability issues for other hardware](https://pagure.io/kernel-fsync/issue/11).

I would instead recommend in the future to just get boards that tend to have the ACS patch as part of their firmware (asrock)

asrock is one of the few motherboard vendors that are GPU passthrough friendly.

**Comment by elevenhsoft** [comment]
Yeah, I'm aware of those motherboards. This is best solution but comes with some additional costs ($$). For now ACS Patch seems awesome, actually I'm always tend to use kernels with this patch, for example Xanmod or Liquorix, or Zen and never had any problems with stability. Maybe the issues are with many more patches in kernel others than acs, I don't know.

Would be nice to see it in Bazzite anyway. From my experience, there was not stability issues or anything like that. Maybe some other setups have.

Bazzite is immutable so low level changes like kernels sounds hard to do and also not recommended. But if you are won't add this patch, well. Sad but I understand :)

**Comment by antheas** [comment]
You cant change the kernel on bazzite dont try. I have tried.

In any case, post the patch and I will review it.

But if it causes instability for other hardware it cannot be added unfortunately

**Comment by elevenhsoft** [comment]
Hello @antheas ,
Thanks for your consideration. I'm used to use patch from `linux-vfio` and `linux-vfio-lts` AUR packages.
For kernel 6.12 there is it: https://aur.archlinux.org/cgit/aur.git/tree/1001-6.8.0-add-acs-overrides.patch?h=linux-vfio
And for LTS: https://aur.archlinux.org/cgit/aur.git/tree/1001-6.6.7-add-acs-overrides.patch?h=linux-vfio-lts

There is few custom kernels which adds this patch. For example, Xanmod, Liquorix, Zen, and few more, even Cachy I think (for Fedora). On every kernel, I did not find any issues. Also, you need to enable this patch with kernel params, so on normal system, you won't need to use it, so it will be disabled. I don't know what issues it can make, but I heard that also, so .... Please review it and consider :) Thank you.

Happy Xmas!

**Comment by antheas** [comment]
Seems harmless enough so I added it

https://github.com/hhd-dev/kernel-bazzite/releases/tag/6.12.6-203
